FROM php:fpm-alpine

RUN apk --update --no-cache add git
RUN docker-php-ext-install pdo_mysql

COPY --from=composer /usr/bin/composer /usr/bin/composer

WORKDIR  /usr/share/saloon-crm/

CMD composer install ; php-fpm

EXPOSE 9000